color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.34953469573520124
  lightness: 0.17525563295930624
  saturation: 0.8030531564727426
  rhythmicContrast: 0.8513059478718787
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Scarf And Earrings Box
layout_spectrum: 0.575676673091948
typography_spectrum: 0.3409560318104923
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/163ab265-104a-4494-8d54-f05b5fbf056a.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/163ab265-104a-4494-8d54-f05b5fbf056a.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4fda6f40-efe7-4779-87b9-54936f70059d.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4fda6f40-efe7-4779-87b9-54936f70059d.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Scarfs
description: Scarf`s from INDIA
github: true
author:
  name: Patel Chittimella
  email: chkvpatel@gmail.com
